### ISSUE TITLE
v3.0.0

### ISSUE THREAD

**Issue by yahwastaken** [winamax/aquedux#40]
The next major release will polish aquedux public API and play as a foundation update to future enhancements and contributions.

Issues:

* [ ] Rework of aquedux-client public API (#30)
* [ ] Rework of aquedux-server public API (#38)
* [ ] Change to a working keep alive and reconnection mechanism (#32)

**Comment by yahwastaken** [comment]
The issue is converted into a milestone.
